### ISSUE TITLE
Не отображаются инициалы игрока

### ISSUE THREAD

**Issue by uskov-anton** [kuznetsov0209/kickermaster#35]
У Ivan Vdovitsa не отображаются инициалы.
![2018-08-20 15 18 27](https://user-images.githubusercontent.com/5119734/44337643-6152e780-a48c-11e8-84b7-a04b734a587d.png)
![2018-08-20 15 18 33](https://user-images.githubusercontent.com/5119734/44337658-6dd74000-a48c-11e8-9b91-54308ce0cece.png)

**Comment by Nezernosh** [comment]
Как можно воспроизвести?
![image](https://user-images.githubusercontent.com/17181569/44386233-f9a3a780-a532-11e8-96c7-5020441f2289.png)
![image](https://user-images.githubusercontent.com/17181569/44386290-26f05580-a533-11e8-8a21-1f4eac8ac5c4.png)

**Comment by kuznetsov0209** [comment]
Там просто ссылка битая была. Думаю, не будем это фиксить. Проблема частично будет исправлена тултипом на аватарке
