### ISSUE TITLE
Добавить переключатель недель на страницы Games и Leaders

### ISSUE THREAD

**Issue by kuznetsov0209** [kuznetsov0209/kickermaster#8]
Сейчас список игр и рейтинг выводится за текущую неделю. Нужно добавить контрол для выбора другой недели для фильтрации. Контрол нужно сделать в виде дэйтпикера.

Выбранную неделю нужно сохранять в стор. Далее этот параметр нужно подставлять в запросы списка игр и рейтинга.

**Comment by Stigie** [comment]
Как располагать дэйтпикер, есть ли макет или требования по оформлению? Часть по фронтенду я сделал, запросы с параметром на сервер отправляются. Серверную часть тоже нужно сделать что ответы с сервера отправлялись? И сервер не поддерживает cors запросы, это нужно самим исправлять?

**Comment by kuznetsov0209** [comment]
Расположение на своё усмотрение

**Comment by kuznetsov0209** [comment]
Должно работать без cors, если фронт и бэкенд на локалхосте

**Comment by kuznetsov0209** [comment]
Если сможешь доработать серверную часть, чтобы фильтрация реально применялась, будет отлично

**Comment by kuznetsov0209** [comment]
Сам PR посмотрю чуть позже, сейчас нет возможности
